// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Thinh_Ecom.Data;

namespace Thinh_Ecom.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "f49e4348-718f-43e3-b1f6-6dc89c5Bb5ff",
                            RoleId = "f49e4348-718f-43e3-b1f6-6dc89c5Bb4fd"
                        },
                        new
                        {
                            UserId = "DE544998-A3CC-4E12-ABB4-0642E57BD222",
                            RoleId = "360E601E-92F2-4F08-832B-604A21293258"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("Thinh_Ecom.Entities.About", b =>
                {
                    b.Property<int>("about_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("about_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("about_Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("about_Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("about_id");

                    b.ToTable("About");

                    b.HasData(
                        new
                        {
                            about_id = 1,
                            about_Description = "The Big Oxmox advised her not to do so, because there were thousands of bad Commas, wild Question Marks and devious Semikoli, but the Little Blind Text didn’t listen. She packed her seven versalia, put her initial into the belt and made herself on the way. \n \n When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove,the headline of Alphabet Village and the subline of her own road,the Line Lane.Pityful a rethoric question ran over her cheek,then she continued her way.",
                            about_Title = "Footwear the leading eCommerce Store around the Globe",
                            about_Url = "https://www.youtube.com/watch?v=F1vcruph8JA"
                        });
                });

            modelBuilder.Entity("Thinh_Ecom.Entities.Bills", b =>
                {
                    b.Property<string>("bill_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("bill_Cancelled")
                        .HasColumnType("bit");

                    b.Property<bool>("bill_Confirmation")
                        .HasColumnType("bit");

                    b.Property<DateTime>("bill_DatetimeOrder")
                        .HasColumnType("datetime2");

                    b.Property<bool>("bill_Delivered")
                        .HasColumnType("bit");

                    b.Property<bool>("bill_Delivering")
                        .HasColumnType("bit");

                    b.Property<int>("bill_Discount")
                        .HasColumnType("int");

                    b.Property<bool>("bill_HideStatus")
                        .HasColumnType("bit");

                    b.Property<string>("bill_Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("bill_PaidTotal")
                        .HasColumnType("int");

                    b.Property<string>("bill_PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_ProductColorlist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_ProductIdlist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_ProductNamelist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_ProductPricelist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_ProductSizelist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_Quantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("bill_Shipping")
                        .HasColumnType("int");

                    b.Property<string>("bill_UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("bill_WaitForConfirmation")
                        .HasColumnType("bit");

                    b.Property<bool>("bill_WaitPickup")
                        .HasColumnType("bit");

                    b.HasKey("bill_Id");

                    b.HasIndex("bill_UserId");

                    b.ToTable("Bills");

                    b.HasData(
                        new
                        {
                            bill_Id = "D269BF93-A5E2-4C4A-8146-9967DDE80D30",
                            bill_Cancelled = false,
                            bill_Confirmation = true,
                            bill_DatetimeOrder = new DateTime(2022, 4, 2, 15, 2, 46, 519, DateTimeKind.Local).AddTicks(4683),
                            bill_Delivered = false,
                            bill_Delivering = false,
                            bill_Discount = 0,
                            bill_HideStatus = false,
                            bill_Note = "",
                            bill_PaidTotal = 2000,
                            bill_PaymentMethod = "Check Payment",
                            bill_ProductColorlist = "Blue|Red|Black|Green",
                            bill_ProductIdlist = "1|2|3|4",
                            bill_ProductNamelist = "product 1|product 2| product 3| product 4",
                            bill_ProductPricelist = "550|450|350|640",
                            bill_ProductSizelist = "7|8|9|14",
                            bill_Quantity = "1|1|2|1",
                            bill_Shipping = 10,
                            bill_UserId = "f49e4348-718f-43e3-b1f6-6dc89c5Bb5ff",
                            bill_WaitForConfirmation = false,
                            bill_WaitPickup = false
                        });
                });

            modelBuilder.Entity("Thinh_Ecom.Entities.Cart", b =>
                {
                    b.Property<string>("cart_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("cart_UserID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("cart_Id");

                    b.HasIndex("cart_UserID");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            cart_Id = "72309286-ECBB-4D20-AD95-2819D31E3400",
                            cart_UserID = "f49e4348-718f-43e3-b1f6-6dc89c5Bb5ff"
                        },
                        new
                        {
                            cart_Id = "D355458F-1DD3-4834-AA28-6DA34B6357FF",
                            cart_UserID = "DE544998-A3CC-4E12-ABB4-0642E57BD222"
                        });
                });

            modelBuilder.Entity("Thinh_Ecom.Entities.CartsDevice", b =>
                {
                    b.Property<string>("cartd_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("cartd_DeviceId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("cartd_Id");

                    b.HasIndex("cartd_DeviceId");

                    b.ToTable("CartsDevice");
                });

            modelBuilder.Entity("Thinh_Ecom.Entities.Categories", b =>
                {
                    b.Property<int>("cg_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cg_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cg_Sale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cg_Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cg_Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            cg_Id = 1,
                            cg_Name = "Pizza",
                            cg_Sale = "",
                            cg_Type = ""
                        },
                        new
                        {
                            cg_Id = 2,
                            cg_Name = "Spaghetti",
                            cg_Sale = "",
                            cg_Type = ""
                        },
                        new
                        {
                            cg_Id = 3,
                            cg_Name = "Side dishes",
                            cg_Sale = "",
                            cg_Type = ""
                        },
                        new
                        {
                            cg_Id = 4,
                            cg_Name = "Drink",
                            cg_Sale = "",
                            cg_Type = ""
                        });
                });

            modelBuilder.Entity("Thinh_Ecom.Entities.ContactSystem", b =>
                {
                    b.Property<int>("Contact_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Contact_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact_Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact_Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Contact_Id");

                    b.ToTable("ContactSystems");

                    b.HasData(
                        new
                        {
                            Contact_Id = 1,
                            Contact_Address = " 123, An Lac A Ward, Binh Tan District, HCM",
                            Contact_Email = "admin@gmail.com",
                            Contact_Phone = "0123456789",
                            Contact_Website = "https://shoes.com"
                        });
                });

            modelBuilder.Entity("Thinh_Ecom.Entities.ContactUsers", b =>
                {
                    b.Property<int>("cu_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cu_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cu_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cu_FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cu_LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cu_Subject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cu_Id");

                    b.ToTable("ContactUsers");

                    b.HasData(
                        new
                        {
                            cu_Id = 1,
                            cu_Description = "Description",
                            cu_Email = "Email",
                            cu_FirstName = "FirstName",
                            cu_LastName = "LastName",
                            cu_Subject = "Subject"
                        });
                });

            modelBuilder.Entity("Thinh_Ecom.Entities.Coupons", b =>
                {
                    b.Property<string>("couponId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("couponCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("couponPrice")
                        .HasColumnType("int");

                    b.HasKey("couponId");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            couponId = "b35e996e-5ff0-481e-bda1-331088b0b025",
                            couponCode = "code10",
                            couponPrice = 10
                        },
                        new
                        {
                            couponId = "6a37744c-ce52-4138-8cb7-679ffce02b97",
                            couponCode = "code50",
                            couponPrice = 50
                        });
                });

            modelBuilder.Entity("Thinh_Ecom.Entities.Device", b =>
                {
                    b.Property<string>("deviceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("deviceAddress1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deviceAddress2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deviceCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deviceCompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deviceCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deviceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("devicePhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("devicePostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deviceState")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("deviceId");

                    b.ToTable("Device");
                });

            modelBuilder.Entity("Thinh_Ecom.Entities.ProductInCart", b =>
                {
                    b.Property<string>("pic_CartId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("pic_ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("pic_amount")
                        .HasColumnType("int");

                    b.Property<string>("pic_color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pic_size")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pic_CartId", "pic_ProductId");

                    b.HasIndex("pic_ProductId");

                    b.ToTable("ProductInCart");

                    b.HasData(
                        new
                        {
                            pic_CartId = "D355458F-1DD3-4834-AA28-6DA34B6357FF",
                            pic_ProductId = "603b0acb-b55b-4cf0-93f6-c2ffa3ffdfc7",
                            pic_amount = 2
                        });
                });

            modelBuilder.Entity("Thinh_Ecom.Entities.ProductInCartDevices", b =>
                {
                    b.Property<string>("picd_CartId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("picd_ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("picd_amount")
                        .HasColumnType("int");

                    b.Property<string>("picd_color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("picd_size")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("picd_CartId", "picd_ProductId");

                    b.HasIndex("picd_ProductId");

                    b.ToTable("ProductInCartDevices");
                });

            modelBuilder.Entity("Thinh_Ecom.Entities.Products", b =>
                {
                    b.Property<string>("pd_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("pd_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pd_Img1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pd_Img2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pd_Img3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pd_Img4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pd_MenuFacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pd_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pd_NameImg1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pd_NameImg2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pd_NameImg3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pd_NameImg4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("pd_Price")
                        .HasColumnType("int");

                    b.Property<int>("pd_Rate")
                        .HasColumnType("int");

                    b.Property<int>("pd_ReducePrice")
                        .HasColumnType("int");

                    b.Property<string>("pd_ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pd_Size")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pd_Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            pd_Id = "603b0acb-b55b-4cf0-93f6-c2ffa3ffdfc7",
                            pd_Description = "pizza-bo",
                            pd_Img1 = "/img/pizza-300x300/pizza-bo.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "Pizza",
                            pd_Price = 10,
                            pd_Rate = 5,
                            pd_ReducePrice = 5,
                            pd_ShortDescription = "",
                            pd_Size = ""
                        },
                        new
                        {
                            pd_Id = "0fcbff44-ca5d-45d2-b337-15a112a69d50",
                            pd_Description = "coca-zero",
                            pd_Img1 = "/img/pizza-300x300/coca-zero.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "Cocacola Zero",
                            pd_Price = 10,
                            pd_Rate = 5,
                            pd_ReducePrice = 5,
                            pd_ShortDescription = "",
                            pd_Size = ""
                        },
                        new
                        {
                            pd_Id = "34d5c948-b7b9-45e8-9fbf-d93bdfa65281",
                            pd_Description = "Extravaganza",
                            pd_Img1 = "/img/pizza-300x300/Extravaganza.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "Extravaganza",
                            pd_Price = 10,
                            pd_Rate = 5,
                            pd_ReducePrice = 5,
                            pd_ShortDescription = "",
                            pd_Size = ""
                        },
                        new
                        {
                            pd_Id = "d3b6bd3a-da88-42ec-a622-3d330ffbe99e",
                            pd_Description = "pfanta-15",
                            pd_Img1 = "/img/pizza-300x300/fanta-15.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "fanta-1.5L",
                            pd_Price = 10,
                            pd_Rate = 5,
                            pd_ReducePrice = 5,
                            pd_ShortDescription = "",
                            pd_Size = ""
                        },
                        new
                        {
                            pd_Id = "a1129d7c-37b8-4376-8a0f-52a521472d9f",
                            pd_Description = "Haft-haft",
                            pd_Img1 = "/img/pizza-300x300/Haft-haft.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "Haft-haft",
                            pd_Price = 10,
                            pd_Rate = 5,
                            pd_ReducePrice = 5,
                            pd_ShortDescription = "",
                            pd_Size = ""
                        },
                        new
                        {
                            pd_Id = "b4face65-ca16-46ee-9926-add44ffc73bd",
                            pd_Description = "Meat-lover",
                            pd_Img1 = "/img/pizza-300x300/Meat-lover.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "Meat-lover",
                            pd_Price = 10,
                            pd_Rate = 5,
                            pd_ReducePrice = 5,
                            pd_ShortDescription = "",
                            pd_Size = ""
                        },
                        new
                        {
                            pd_Id = "0a6405b2-5a0c-4dfe-979e-eac362499fbd",
                            pd_Description = "MENU-PC",
                            pd_Img1 = "/img/pizza-300x300/MENU-PC.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "MENU-PC",
                            pd_Price = 10,
                            pd_Rate = 5,
                            pd_ReducePrice = 5,
                            pd_ShortDescription = "",
                            pd_Size = ""
                        },
                        new
                        {
                            pd_Id = "d9795052-31d0-408d-8bf4-93c2836b701f",
                            pd_Description = "MENU-PC-BBQ",
                            pd_Img1 = "/img/pizza-300x300/MENU-PC-BBQ.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "MENU-PC-BBQ",
                            pd_Price = 10,
                            pd_Rate = 5,
                            pd_ReducePrice = 5,
                            pd_ShortDescription = "",
                            pd_Size = ""
                        },
                        new
                        {
                            pd_Id = "f539ed6e-0894-46e5-a3d5-5f8a3a138857",
                            pd_Description = "MENU-PC-my",
                            pd_Img1 = "/img/pizza-300x300/MENU-PC-my.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "MENU-PC-my",
                            pd_Price = 10,
                            pd_Rate = 5,
                            pd_ReducePrice = 5,
                            pd_ShortDescription = "",
                            pd_Size = ""
                        },
                        new
                        {
                            pd_Id = "c7c03110-29df-4de8-ac50-174a894dfd39",
                            pd_Description = "MENU-PC-Pho-Mai",
                            pd_Img1 = "/img/pizza-300x300/MENU-PC-Pho-Mai.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "MENU-PC-Pho-Mai",
                            pd_Price = 10,
                            pd_Rate = 5,
                            pd_ReducePrice = 5,
                            pd_ShortDescription = "",
                            pd_Size = ""
                        },
                        new
                        {
                            pd_Id = "4aad1c9f-41b7-4a4b-b3dc-3a6e3caff0c6",
                            pd_Description = "Ocean-mania",
                            pd_Img1 = "/img/pizza-300x300/Ocean-mania.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "Ocean-mania",
                            pd_Price = 10,
                            pd_Rate = 5,
                            pd_ReducePrice = 5,
                            pd_ShortDescription = "",
                            pd_Size = ""
                        },
                        new
                        {
                            pd_Id = "ebd9c0c2-aa14-4c22-b316-0cd28ee86afd",
                            pd_Description = "Okonomiyaki",
                            pd_Img1 = "/img/pizza-300x300/Okonomiyaki.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "Okonomiyaki",
                            pd_Price = 10,
                            pd_Rate = 5,
                            pd_ReducePrice = 5,
                            pd_ShortDescription = "",
                            pd_Size = ""
                        },
                        new
                        {
                            pd_Id = "1b39ae47-2408-418f-a46f-904f44e91011",
                            pd_Description = "pasta-bo-bam",
                            pd_Img1 = "/img/pizza-300x300/pasta-bo-bam.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "pasta",
                            pd_Price = 10,
                            pd_Rate = 5,
                            pd_ReducePrice = 5,
                            pd_ShortDescription = "",
                            pd_Size = ""
                        },
                        new
                        {
                            pd_Id = "9a035806-d78c-435d-8fe7-8911d925ef33",
                            pd_Description = "pasta-hai-san",
                            pd_Img1 = "/img/pizza-300x300/pasta-hai-san.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "pasta-hai-san",
                            pd_Price = 10,
                            pd_Rate = 5,
                            pd_ReducePrice = 5,
                            pd_ShortDescription = "",
                            pd_Size = ""
                        },
                        new
                        {
                            pd_Id = "0ee3343b-6dd2-4bce-81eb-245bfbcc11c2",
                            pd_Description = "pasta-rau-cu",
                            pd_Img1 = "/img/pizza-300x300/pasta-rau-cu.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "pasta-rau-cu",
                            pd_Price = 10,
                            pd_Rate = 5,
                            pd_ReducePrice = 5,
                            pd_ShortDescription = "",
                            pd_Size = ""
                        },
                        new
                        {
                            pd_Id = "a7cc4c9e-985e-437f-972f-2b8e8eb253f4",
                            pd_Description = "pizza-bo",
                            pd_Img1 = "/img/pizza-300x300/pizza-bo.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "pizza-bo",
                            pd_Price = 10,
                            pd_Rate = 5,
                            pd_ReducePrice = 5,
                            pd_ShortDescription = "",
                            pd_Size = ""
                        },
                        new
                        {
                            pd_Id = "c4dbd76c-01bb-4baa-9c33-8312bd541f72",
                            pd_Description = "Pizzaminsea",
                            pd_Img1 = "/img/pizza-300x300/Pizzaminsea.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "Pizzaminsea",
                            pd_Price = 10,
                            pd_Rate = 5,
                            pd_ReducePrice = 5,
                            pd_ShortDescription = "",
                            pd_Size = ""
                        },
                        new
                        {
                            pd_Id = "168625c0-ae5c-4cd2-846c-d6864d2b2975",
                            pd_Description = "Sprite-15L",
                            pd_Img1 = "/img/pizza-300x300/Sprite-15L.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "Sprite-15L",
                            pd_Price = 10,
                            pd_Rate = 5,
                            pd_ReducePrice = 5,
                            pd_ShortDescription = "",
                            pd_Size = ""
                        });
                });

            modelBuilder.Entity("Thinh_Ecom.Entities.ProductsInCategories", b =>
                {
                    b.Property<string>("pic_productId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("pic_CategoriesId")
                        .HasColumnType("int");

                    b.HasKey("pic_productId", "pic_CategoriesId");

                    b.HasIndex("pic_CategoriesId");

                    b.ToTable("ProductsInCategories");

                    b.HasData(
                        new
                        {
                            pic_productId = "603b0acb-b55b-4cf0-93f6-c2ffa3ffdfc7",
                            pic_CategoriesId = 1
                        },
                        new
                        {
                            pic_productId = "34d5c948-b7b9-45e8-9fbf-d93bdfa65281",
                            pic_CategoriesId = 1
                        },
                        new
                        {
                            pic_productId = "a1129d7c-37b8-4376-8a0f-52a521472d9f",
                            pic_CategoriesId = 1
                        },
                        new
                        {
                            pic_productId = "b4face65-ca16-46ee-9926-add44ffc73bd",
                            pic_CategoriesId = 1
                        },
                        new
                        {
                            pic_productId = "4aad1c9f-41b7-4a4b-b3dc-3a6e3caff0c6",
                            pic_CategoriesId = 1
                        },
                        new
                        {
                            pic_productId = "ebd9c0c2-aa14-4c22-b316-0cd28ee86afd",
                            pic_CategoriesId = 1
                        },
                        new
                        {
                            pic_productId = "a7cc4c9e-985e-437f-972f-2b8e8eb253f4",
                            pic_CategoriesId = 1
                        },
                        new
                        {
                            pic_productId = "c4dbd76c-01bb-4baa-9c33-8312bd541f72",
                            pic_CategoriesId = 1
                        },
                        new
                        {
                            pic_productId = "c4dbd76c-01bb-4baa-9c33-8312bd541f72",
                            pic_CategoriesId = 2
                        },
                        new
                        {
                            pic_productId = "1b39ae47-2408-418f-a46f-904f44e91011",
                            pic_CategoriesId = 2
                        },
                        new
                        {
                            pic_productId = "9a035806-d78c-435d-8fe7-8911d925ef33",
                            pic_CategoriesId = 2
                        },
                        new
                        {
                            pic_productId = "0ee3343b-6dd2-4bce-81eb-245bfbcc11c2",
                            pic_CategoriesId = 2
                        },
                        new
                        {
                            pic_productId = "0a6405b2-5a0c-4dfe-979e-eac362499fbd",
                            pic_CategoriesId = 3
                        },
                        new
                        {
                            pic_productId = "d9795052-31d0-408d-8bf4-93c2836b701f",
                            pic_CategoriesId = 3
                        },
                        new
                        {
                            pic_productId = "f539ed6e-0894-46e5-a3d5-5f8a3a138857",
                            pic_CategoriesId = 3
                        },
                        new
                        {
                            pic_productId = "c7c03110-29df-4de8-ac50-174a894dfd39",
                            pic_CategoriesId = 3
                        },
                        new
                        {
                            pic_productId = "0fcbff44-ca5d-45d2-b337-15a112a69d50",
                            pic_CategoriesId = 4
                        },
                        new
                        {
                            pic_productId = "d3b6bd3a-da88-42ec-a622-3d330ffbe99e",
                            pic_CategoriesId = 4
                        },
                        new
                        {
                            pic_productId = "168625c0-ae5c-4cd2-846c-d6864d2b2975",
                            pic_CategoriesId = 4
                        });
                });

            modelBuilder.Entity("Thinh_Ecom.Entities.ReviewInproduct", b =>
                {
                    b.Property<string>("rip_ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("rip_ReviewId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("rip_ProductId", "rip_ReviewId");

                    b.HasIndex("rip_ReviewId");

                    b.ToTable("ReviewInproduct");

                    b.HasData(
                        new
                        {
                            rip_ProductId = "603b0acb-b55b-4cf0-93f6-c2ffa3ffdfc7",
                            rip_ReviewId = "EEBA6608-AB75-4E83-909F-604B1A06F16C"
                        },
                        new
                        {
                            rip_ProductId = "603b0acb-b55b-4cf0-93f6-c2ffa3ffdfc7",
                            rip_ReviewId = "9EED8607-D2BB-45EE-AEE3-C59D858A7F97"
                        },
                        new
                        {
                            rip_ProductId = "603b0acb-b55b-4cf0-93f6-c2ffa3ffdfc7",
                            rip_ReviewId = "C2A543C2-B1E2-4DC5-A131-9137E4673FA6"
                        });
                });

            modelBuilder.Entity("Thinh_Ecom.Entities.Reviews", b =>
                {
                    b.Property<string>("review_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("review_Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("review_HideStatus")
                        .HasColumnType("bit");

                    b.Property<string>("review_ReviewType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("review_UploadTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("review_UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("review_id");

                    b.HasIndex("review_UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            review_id = "EEBA6608-AB75-4E83-909F-604B1A06F16C",
                            review_Comment = "Good1",
                            review_HideStatus = false,
                            review_ReviewType = "Review",
                            review_UploadTime = new DateTime(2020, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            review_UserId = "DE544998-A3CC-4E12-ABB4-0642E57BD222"
                        },
                        new
                        {
                            review_id = "9EED8607-D2BB-45EE-AEE3-C59D858A7F97",
                            review_Comment = "Good2",
                            review_HideStatus = false,
                            review_ReviewType = "Review",
                            review_UploadTime = new DateTime(2020, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            review_UserId = "f49e4348-718f-43e3-b1f6-6dc89c5Bb5ff"
                        },
                        new
                        {
                            review_id = "C2A543C2-B1E2-4DC5-A131-9137E4673FA6",
                            review_Comment = "Good3",
                            review_HideStatus = false,
                            review_ReviewType = "Review",
                            review_UploadTime = new DateTime(2020, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            review_UserId = "DE544998-A3CC-4E12-ABB4-0642E57BD222"
                        });
                });

            modelBuilder.Entity("Thinh_Ecom.Entities.Shipping", b =>
                {
                    b.Property<string>("ship_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ship_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ship_Price")
                        .HasColumnType("int");

                    b.HasKey("ship_Id");

                    b.ToTable("Shipping");

                    b.HasData(
                        new
                        {
                            ship_Id = "7CF94A7D-9239-446E-A404-086518F84652",
                            ship_Name = "Ship",
                            ship_Price = 5
                        });
                });

            modelBuilder.Entity("Thinh_Ecom.Entities.SubReview", b =>
                {
                    b.Property<string>("subReview_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("subReview_Commnet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("subReview_DateCommnet")
                        .HasColumnType("datetime2");

                    b.Property<bool>("subReview_HideStatus")
                        .HasColumnType("bit");

                    b.Property<string>("subReview_UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("subreview_SubReviewType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("subReview_Id");

                    b.HasIndex("subReview_UserId");

                    b.ToTable("SubReview");

                    b.HasData(
                        new
                        {
                            subReview_Id = "759034f8-4261-4796-8f0a-efed4048b2a6",
                            subReview_Commnet = "subreview 1",
                            subReview_DateCommnet = new DateTime(2020, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            subReview_HideStatus = false,
                            subReview_UserId = "DE544998-A3CC-4E12-ABB4-0642E57BD222",
                            subreview_SubReviewType = "SubReview"
                        },
                        new
                        {
                            subReview_Id = "1a24971d-0c45-459a-a567-a44b66225a8f",
                            subReview_Commnet = "subreview 3",
                            subReview_DateCommnet = new DateTime(2020, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            subReview_HideStatus = false,
                            subReview_UserId = "f49e4348-718f-43e3-b1f6-6dc89c5Bb5ff",
                            subreview_SubReviewType = "SubReview"
                        },
                        new
                        {
                            subReview_Id = "45951868-3d3b-4ef1-9fdd-b08667aa96aa",
                            subReview_Commnet = "subreview 3",
                            subReview_DateCommnet = new DateTime(2020, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            subReview_HideStatus = false,
                            subReview_UserId = "DE544998-A3CC-4E12-ABB4-0642E57BD222",
                            subreview_SubReviewType = "SubReview"
                        });
                });

            modelBuilder.Entity("Thinh_Ecom.Entities.SubReviewInReview", b =>
                {
                    b.Property<string>("SRiR_ReviewId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SRiR_SubReviewId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SRiR_ReviewId", "SRiR_SubReviewId");

                    b.HasIndex("SRiR_SubReviewId");

                    b.ToTable("SubReviewInReview");

                    b.HasData(
                        new
                        {
                            SRiR_ReviewId = "EEBA6608-AB75-4E83-909F-604B1A06F16C",
                            SRiR_SubReviewId = "759034f8-4261-4796-8f0a-efed4048b2a6"
                        },
                        new
                        {
                            SRiR_ReviewId = "EEBA6608-AB75-4E83-909F-604B1A06F16C",
                            SRiR_SubReviewId = "1a24971d-0c45-459a-a567-a44b66225a8f"
                        },
                        new
                        {
                            SRiR_ReviewId = "9EED8607-D2BB-45EE-AEE3-C59D858A7F97",
                            SRiR_SubReviewId = "45951868-3d3b-4ef1-9fdd-b08667aa96aa"
                        });
                });

            modelBuilder.Entity("Thinh_Ecom.EntitiesThinh_Ecom.Entities.AppRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("AppRole");

                    b.HasData(
                        new
                        {
                            Id = "f49e4348-718f-43e3-b1f6-6dc89c5Bb4fd",
                            ConcurrencyStamp = "ed072818-3aac-4158-8f33-9d253a3944d5",
                            Name = "staff",
                            Description = "Staff"
                        },
                        new
                        {
                            Id = "360E601E-92F2-4F08-832B-604A21293258",
                            ConcurrencyStamp = "21a7995b-c405-47d0-87d2-2c5bccb4fe75",
                            Name = "admin",
                            Description = "admin"
                        });
                });

            modelBuilder.Entity("Thinh_Ecom.Entities.AppUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<DateTime>("DoB")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_Address1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_State")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("AppUser");

                    b.HasData(
                        new
                        {
                            Id = "DE544998-A3CC-4E12-ABB4-0642E57BD222",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1494b7c1-5daa-46b1-a20f-dbb66d39ab46",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEHi+sG6N2Wmry7QZVnUIxkTdFUsbTwo/jiE+gN4vv2RWV7MUQbOaWTDWghWULSoi9w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f1d870e9-aea8-4087-a21e-5b6870592979",
                            TwoFactorEnabled = false,
                            UserName = "Admin",
                            DoB = new DateTime(2020, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "admin",
                            LastName = "admin"
                        },
                        new
                        {
                            Id = "f49e4348-718f-43e3-b1f6-6dc89c5Bb5ff",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a87fad47-256d-4214-8c73-34ec991bf30e",
                            Email = "staff@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "STAFF@GMAIL.COM",
                            NormalizedUserName = "STAFF@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEJO0CNdyZqCvGMtE0gRkNSrn9Cbey6WusBPd3pyqNmXGEh5ynHiv9WK/tjjmoAe+pg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9d564e85-9363-4982-b68e-7553d7566f04",
                            TwoFactorEnabled = false,
                            UserName = "Staff",
                            DoB = new DateTime(2020, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "staff",
                            LastName = "staff"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Thinh_Ecom.Entities.Bills", b =>
                {
                    b.HasOne("Thinh_Ecom.Entities.AppUser", "AppUserB")
                        .WithMany("BillsAU")
                        .HasForeignKey("bill_UserId");

                    b.Navigation("AppUserB");
                });

            modelBuilder.Entity("Thinh_Ecom.Entities.Cart", b =>
                {
                    b.HasOne("Thinh_Ecom.Entities.AppUser", "AppUserC")
                        .WithMany("CartU")
                        .HasForeignKey("cart_UserID");

                    b.Navigation("AppUserC");
                });

            modelBuilder.Entity("Thinh_Ecom.Entities.CartsDevice", b =>
                {
                    b.HasOne("Thinh_Ecom.Entities.Device", "DeviceCD")
                        .WithMany("CartsDeviceD")
                        .HasForeignKey("cartd_DeviceId");

                    b.Navigation("DeviceCD");
                });

            modelBuilder.Entity("Thinh_Ecom.Entities.ProductInCart", b =>
                {
                    b.HasOne("Thinh_Ecom.Entities.Cart", "CartPICart")
                        .WithMany("ProductInCartC")
                        .HasForeignKey("pic_CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thinh_Ecom.Entities.Products", "ProductsPICart")
                        .WithMany("ProductInCartP")
                        .HasForeignKey("pic_ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CartPICart");

                    b.Navigation("ProductsPICart");
                });

            modelBuilder.Entity("Thinh_Ecom.Entities.ProductInCartDevices", b =>
                {
                    b.HasOne("Thinh_Ecom.Entities.CartsDevice", "CartsDevicePICD")
                        .WithMany("ProductInCartDevicesCD")
                        .HasForeignKey("picd_CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thinh_Ecom.Entities.Products", "ProductsPICD")
                        .WithMany("ProductInCartDevicesP")
                        .HasForeignKey("picd_ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CartsDevicePICD");

                    b.Navigation("ProductsPICD");
                });

            modelBuilder.Entity("Thinh_Ecom.Entities.ProductsInCategories", b =>
                {
                    b.HasOne("Thinh_Ecom.Entities.Categories", "CategoriesPIC")
                        .WithMany("ProductsInCategoriesC")
                        .HasForeignKey("pic_CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thinh_Ecom.Entities.Products", "ProductsPIC")
                        .WithMany("ProductsInCategoriesP")
                        .HasForeignKey("pic_productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriesPIC");

                    b.Navigation("ProductsPIC");
                });

            modelBuilder.Entity("Thinh_Ecom.Entities.ReviewInproduct", b =>
                {
                    b.HasOne("Thinh_Ecom.Entities.Products", "ProductsRIP")
                        .WithMany("ReviewInproductP")
                        .HasForeignKey("rip_ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thinh_Ecom.Entities.Reviews", "ReviewsRIP")
                        .WithMany("ReviewInproductR")
                        .HasForeignKey("rip_ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductsRIP");

                    b.Navigation("ReviewsRIP");
                });

            modelBuilder.Entity("Thinh_Ecom.Entities.Reviews", b =>
                {
                    b.HasOne("Thinh_Ecom.Entities.AppUser", "AppUserR")
                        .WithMany("ReviewsU")
                        .HasForeignKey("review_UserId");

                    b.Navigation("AppUserR");
                });

            modelBuilder.Entity("Thinh_Ecom.Entities.SubReview", b =>
                {
                    b.HasOne("Thinh_Ecom.Entities.AppUser", "AppUserSR")
                        .WithMany("SubReviewSR")
                        .HasForeignKey("subReview_UserId");

                    b.Navigation("AppUserSR");
                });

            modelBuilder.Entity("Thinh_Ecom.Entities.SubReviewInReview", b =>
                {
                    b.HasOne("Thinh_Ecom.Entities.Reviews", "Reviews")
                        .WithMany("SubReviewInReview")
                        .HasForeignKey("SRiR_ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thinh_Ecom.Entities.SubReview", "SubReview")
                        .WithMany("SubReviewInReview")
                        .HasForeignKey("SRiR_SubReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reviews");

                    b.Navigation("SubReview");
                });

            modelBuilder.Entity("Thinh_Ecom.Entities.Cart", b =>
                {
                    b.Navigation("ProductInCartC");
                });

            modelBuilder.Entity("Thinh_Ecom.Entities.CartsDevice", b =>
                {
                    b.Navigation("ProductInCartDevicesCD");
                });

            modelBuilder.Entity("Thinh_Ecom.Entities.Categories", b =>
                {
                    b.Navigation("ProductsInCategoriesC");
                });

            modelBuilder.Entity("Thinh_Ecom.Entities.Device", b =>
                {
                    b.Navigation("CartsDeviceD");
                });

            modelBuilder.Entity("Thinh_Ecom.Entities.Products", b =>
                {
                    b.Navigation("ProductInCartDevicesP");

                    b.Navigation("ProductInCartP");

                    b.Navigation("ProductsInCategoriesP");

                    b.Navigation("ReviewInproductP");
                });

            modelBuilder.Entity("Thinh_Ecom.Entities.Reviews", b =>
                {
                    b.Navigation("ReviewInproductR");

                    b.Navigation("SubReviewInReview");
                });

            modelBuilder.Entity("Thinh_Ecom.Entities.SubReview", b =>
                {
                    b.Navigation("SubReviewInReview");
                });

            modelBuilder.Entity("Thinh_Ecom.Entities.AppUser", b =>
                {
                    b.Navigation("BillsAU");

                    b.Navigation("CartU");

                    b.Navigation("ReviewsU");

                    b.Navigation("SubReviewSR");
                });
#pragma warning restore 612, 618
        }
    }
}
